"""Add job posting fields to requirements

Revision ID: 3c1426cc6846
Revises: d14639c18ccb
Create Date: 2026-01-07 20:41:01.903130+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c1426cc6846'
down_revision = 'd14639c18ccb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the PostingStatus enum type first
    posting_status_enum = postgresql.ENUM('NOT_POSTED', 'DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', name='postingstatus')
    posting_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.alter_column('approvals', 'approval_stage',
               existing_type=postgresql.ENUM('department_head', 'finance', 'executive', name='approvalstage'),
               nullable=False)
    op.add_column('requirements', sa.Column('posting_status', sa.Enum('NOT_POSTED', 'DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', name='postingstatus'), nullable=False, server_default='NOT_POSTED'))
    op.add_column('requirements', sa.Column('posting_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('requirements', sa.Column('job_posting_url', sa.String(length=500), nullable=True))
    op.add_column('requirements', sa.Column('posting_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'posting_details')
    op.drop_column('requirements', 'job_posting_url')
    op.drop_column('requirements', 'posting_channels')
    op.drop_column('requirements', 'posting_status')
    op.alter_column('approvals', 'approval_stage',
               existing_type=postgresql.ENUM('department_head', 'finance', 'executive', name='approvalstage'),
               nullable=True)
    
    # Drop the PostingStatus enum type
    posting_status_enum = postgresql.ENUM('NOT_POSTED', 'DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', name='postingstatus')
    posting_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
